### ISSUE TITLE
Implementation for getting sink volume

### ISSUE THREAD

**Issue by twister21** [PhilippMundhenk/PulseAudioJava#1]
Hello,

is there any opportunity to get the volume of a given sink? Or will it be implemented in a future version?

**Comment by PhilippMundhenk** [comment]
Unfortunately, there seems to be no easy way to directly read the volume for a sink in PulseAudio (compare https://unix.stackexchange.com/questions/132230/read-out-pulseaudio-volume-from-commandline-i-want-pactl-get-sink-volume). 
As in my application my process was the only one using PulseAudio, I had full control over the sinks. Thus, I simply stored the volume myself.

I do not currently plan on implementing reading volume. However, with the examples from StackOverflow above, it should not be too difficult. Are you interested in forking the repository and implementing it yourself? I would be happy to accept a pull request!

**Comment by twister21** [comment]
I've used a similar solution for reading the volume and the state of mute. You just need to search for "Volume" and "Mute" in the output of "pactl list sinks".

**Comment by PhilippMundhenk** [comment]
Would you like to integrate this into PulseAudioJava? You can fork the repository, integrate it and create a pull request.

btw: I am not sure if this is independent of the language used on the machine. Searching for the terms "Volume" and "Mute" might only work on systems set to English. Nevertheless, it is a good start and better than the current non-existence of such a feature.

**Comment by twister21** [comment]
Yes, that's the problem of this solution. Unfortunately, I haven't got enough time to fork the project since there a lot of entries on my to-do list.
